name: Generate Art Stats HTML

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install beautifulsoup4 requests

      - name: Run script
        run: python generate_art_statistics.py

      - name: Commit HTML output
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add art_statistics_snippet.html
          git commit -m "Update art statistics snippet"
          git push
